### ISSUE TITLE
result setup exe after putting in a win32/64 bit electron gives wacatac trojan warning on windows defender

### ISSUE THREAD

**Issue by riwi07** [TurboWarp/packager-extras#40] opened 2022-09-14 00:37 UTC
When I select a zip file that was packaged with electron for win 32 and 64 bit and turn it into a standalone setup exe, windows defender gives me a warning for a wacatac trojan when executing it. I run windows 10. Is this an issue with the packager extras, windows defender, or is my computer feeding any exe generated by it the trojan? Old setup exes from about a month ago do not have this issue.
![Screenshot (882)](https://user-images.githubusercontent.com/113483852/190033244-78290930-5cf9-41a7-8cb9-e9c6e7c68b3b.png)

**Comment by PPPDUD** [comment] 2022-10-18 19:45
If you have such issues, please go to #27.

**Comment by PPPDUD** [comment] 2022-11-19 13:47
@GarboMuffin Please close this.

**Comment by PPPDUD** [comment] 2022-11-23 21:46
> @GarboMuffin Please close this.

@GarboMuffin

**Comment by GarboMuffin** [comment] 2023-03-05 22:36
Closing as a duplicate of #27

**Closed by GarboMuffin** 2023-03-05 22:36 UTC
