### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by arsha5340** [TurboWarp/packager-extras#127] opened 2024-03-20 07:17 UTC
![Screenshot 2024-03-20 103304](https://github.com/TurboWarp/packager-extras/assets/137794706/bc7be050-800b-425f-a8a3-cf9dedea187c)

**Comment by ntvmb** [comment] 2024-05-11 23:38
Defender loves to give false positives. Also, this is technically a duplicate of #27.

**Closed** 2024-05-12 00:08 UTC
