### ISSUE TITLE
You should make it be able to create Linux or Android installers

### ISSUE THREAD

**Issue by TheGreatSpaget** [TurboWarp/packager-extras#147] opened 2024-06-23 03:41 UTC
it would be nice it it could not only do installers for windows but also make an installer app to run on Linux or an APK file to install on Android

**Comment by GarboMuffin** [comment] 2024-07-12 01:26
duplicate of https://github.com/TurboWarp/packager/issues/2

**Closed by GarboMuffin** 2024-07-12 01:26 UTC
