### ISSUE TITLE
idk what happend 

### ISSUE THREAD

**Issue by mxqontopgames** [TurboWarp/packager-extras#76] opened 2023-05-16 21:55 UTC
![image](https://github.com/TurboWarp/packager-extras/assets/133819946/ca550372-de19-4a1f-bca2-54b23040ac6a)

**Comment by GarboMuffin** [comment] 2024-03-03 02:24
we think this is related to antiviruses; closing as a duplicate of https://github.com/TurboWarp/packager-extras/issues/27

**Closed by GarboMuffin** 2024-03-03 02:24 UTC
