### ISSUE TITLE
GPU child proccess  crashed: crashed (-1073741515)

### ISSUE THREAD

**Issue by XPerienceJH** [TurboWarp/packager-extras#33] opened 2022-07-24 19:29 UTC
Every time I go throught the setup process for my game and then when I click on my game ith keeps coming up with the error message 'GPU child proccess crashed: crashed (-1073741515)' does anyone know how to fix this?

**Comment by GarboMuffin** [comment] 2022-07-24 19:32
Does it crash if you don't use extras and run the app from the extracted zip?

**Comment by XPerienceJH** [comment] 2022-07-24 19:39
> Does it crash if you don't use extras and run the app from the extracted zip?

no its perfectly fine then, but i would very much prefer to have a single file then a whole zip file

**Comment by XPerienceJH** [comment] 2022-07-24 22:54
do you by any chance know how to solve this issue?

**Comment by GarboMuffin** [comment] 2022-07-25 20:50
We have a general hypothesis about the cause of this type of crash. Does your project have a lot of vector costumes in it, and are those costumes being rendered at large sizes?

I don't see any reason why using extras or not would make a difference as to whether your project crashes or not

**Comment by GarboMuffin** [comment] 2022-07-26 03:10
What if you tried using "Electron Windows application (64-bit only, not recommended)" in "Other environments"?

**Comment by XPerienceJH** [comment] 2022-07-26 14:43
> We have a general hypothesis about the cause of this type of crash. Does your project have a lot of vector costumes in it, and are those costumes being rendered at large sizes?
> 
> I don't see any reason why using extras or not would make a difference as to whether your project crashes or not

Yes

**Comment by GarboMuffin** [comment] 2024-03-03 02:21
uh, if this still happens & you still care, let me know, otherwise I have to close this as unreproducible

**Closed by GarboMuffin** 2024-03-03 02:21 UTC
