### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by CreatorYo** [TurboWarp/packager-extras#109] opened 2024-01-01 21:29 UTC
It keeps showing "Virus Detected" so it won't let me run my file.

**Comment by GarboMuffin** [comment] 2024-01-01 22:01
what antivirus and what virus?

**Comment by CreatorYo** [comment] 2024-01-01 22:19
Windows Antivirus.

**Comment by FarbrikStrom** [comment] 2024-01-14 13:20
I have the same Problem. I have Trojanaer

**Comment by GarboMuffin** [comment] 2024-03-03 02:19
I'm going to close this as a duplicate of https://github.com/TurboWarp/packager-extras/issues/27

**Closed by GarboMuffin** 2024-03-03 02:19 UTC
